-- User test data
INSERT INTO ROLE (TYPE) VALUES ('ADMINISTRATOR'), ('PROJECT_MANAGER'), ('TEST_MANAGER'), ('DEVELOPER'), ('TESTER');

INSERT INTO PERMISSION (TYPE) VALUES ('PERMISSION_MANAGEMENT'), ('USER_MANAGEMENT'), ('BUG_MANAGEMENT'), ('BUG_CLOSE'), ('BUG_EXPORT_PDF');

INSERT INTO USER (EMAIL, FIRSTNAME, LASTNAME, MOBILENUMBER, PASSWORD, STATUS, USERNAME) VALUES('paul@msggroup.com', 'Paul', 'Ghemes', '0741023453', 'ŒvéÀDe‡ªNNŸÑ;', 'ACTIVE', 'ghemep');

INSERT INTO USER (EMAIL, FIRSTNAME, LASTNAME, MOBILENUMBER, PASSWORD, STATUS, USERNAME) VALUES('cristi@msggroup.com', 'Cristian', 'Macarie', '0741023453', 'ŒvéÀDe‡ªNNŸÑ;', 'ACTIVE', 'macarc');

INSERT INTO USER (EMAIL, FIRSTNAME, LASTNAME, MOBILENUMBER, PASSWORD, STATUS, USERNAME) VALUES('tihamer@msggroup.com', 'Tihamer', 'Both', '0741023453', 'ŒvéÀDe‡ªNNŸÑ;', 'ACTIVE', 'bothti');

INSERT INTO USER (EMAIL, FIRSTNAME, LASTNAME, MOBILENUMBER, PASSWORD, STATUS, USERNAME) VALUES('botond@msggroup.com', 'Botond', 'Laszlo', '0741023453', 'ŒvéÀDe‡ªNNŸÑ;', 'ACTIVE', 'laszlb');

INSERT INTO USER (EMAIL, FIRSTNAME, LASTNAME, MOBILENUMBER, PASSWORD, STATUS, USERNAME) VALUES('sanziana@msggroup.com', 'Sanziana', 'Sorea', '0741023453', 'ŒvéÀDe‡ªNNŸÑ;', 'ACTIVE', 'soreas');

INSERT INTO USER (EMAIL, FIRSTNAME, LASTNAME, MOBILENUMBER, PASSWORD, STATUS, USERNAME) VALUES('oana@msggroup.com', 'Oana', 'Lung', '0741023453', 'ŒvéÀDe‡ªNNŸÑ;', 'ACTIVE', 'lungoa');

INSERT INTO USER (EMAIL, FIRSTNAME, LASTNAME, MOBILENUMBER, PASSWORD, STATUS, USERNAME) VALUES('admin@msggroup.com', 'Admin', 'Admin', '0768594837', 'ŒvéÀDe‡ªNNŸÑ;', 'ACTIVE', 'admina');





INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (1, 2);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (1, 1);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (2, 3);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (2, 4);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (2, 5);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (2, 1);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (3, 3);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (3, 4);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (3, 5);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (4, 3);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (4, 5);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (5, 3);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (5, 4);
INSERT INTO ROLE_PERMISSION (ROLES_ID, PERMISSIONS_ID) VALUES (5, 5);


INSERT INTO USER_ROLE (ROLES_ID, USERS_ID) VALUES (1, 7);
INSERT INTO USER_ROLE (ROLES_ID, USERS_ID) VALUES (2, 1);
INSERT INTO USER_ROLE (ROLES_ID, USERS_ID) VALUES (3, 2);
INSERT INTO USER_ROLE (ROLES_ID, USERS_ID) VALUES (4, 3);
INSERT INTO USER_ROLE (ROLES_ID, USERS_ID) VALUES (4, 4);
INSERT INTO USER_ROLE (ROLES_ID, USERS_ID) VALUES (5, 5);
INSERT INTO USER_ROLE (ROLES_ID, USERS_ID) VALUES (5, 6);


-- other tables TODO